apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-data-pvc
  namespace: federated-learning
spec:
  storageClassName: local-path
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 600Gi
  volumeName: master-data-pv