apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-data-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 600Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/e/dizert/federated-learning-medical-images/CheXpert-v1.0   # absolute host path
