apiVersion: apps/v1
kind: Deployment
metadata:
  name: federated-aggregator
  namespace: federated-learning
spec:
  replicas: 1  # Single aggregator instance
  selector:
    matchLabels:
      app: federated-aggregator
  template:
    metadata:
      labels:
        app: federated-aggregator
    spec:
      containers:
      - name: aggregator
        image: federated-aggregator:latest
        ports:
          - containerPort: 50051
            name: grpc
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m" 
