apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: medical-unit
  namespace: federated-learning
spec:
  serviceName: medical-unit
  replicas: 5 # 5 medical units
  selector:
    matchLabels:
      app: medical-unit
  template:
    metadata:
      labels:
        app: medical-unit
    spec:
      volumes:
        - name: client-data
          persistentVolumeClaim:
            claimName: master-data-pvc
      runtimeClassName: nvidia
      containers:
      - name: medical-client
        image: medical-unit-image:latest
        imagePullPolicy: IfNotPresent # ensures it uses local image if available
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CLIENT_DATA_ROOT
            value: "/dataset"
          - name: LOCAL_BATCH_SIZE
            value: "8"
          - name: SHUFFLE_BUFFER
            value: "32"
          - name: TF_FORCE_GPU_ALLOW_GROWTH
            value: "true"
        # mount the shared dataset here
        volumeMounts:
          - name: client-data
            mountPath: /dataset
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            nvidia.com/gpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: "1"

