apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: federated-learning
spec:
  selector:
    app: federated-aggregator
  ports:
    - protocol: TCP
      port: 50051        # the service is exposed on 50051 for gRPC
      targetPort: 50051  # traffic is forwarded to this port inside the aggregator container
      name: grpc
  type: ClusterIP  # internal service
